# Generated by Django 3.2 on 2021-07-18 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='news/')),
                ('title', models.CharField(default='News title', max_length=250)),
                ('slug', models.SlugField(max_length=250)),
                ('newsBody', models.TextField()),
                ('publish', models.BooleanField(default=False)),
                ('published', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-published'],
            },
        ),
    ]
