# Generated by Django 3.2 on 2021-07-18 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runo', '0002_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='desc',
            field=models.CharField(default='short description of the news', max_length=250),
        ),
    ]
