# Generated by Django 3.2 on 2021-07-19 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runo', '0004_importantdates'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=100)),
                ('school_address', models.CharField(max_length=250)),
                ('school_phone', models.CharField(max_length=18)),
                ('school_email', models.EmailField(max_length=254)),
            ],
        ),
    ]
