# Generated by Django 3.2 on 2021-07-20 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runo', '0005_footerdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('galleryImage', models.ImageField(upload_to='gallery/')),
                ('name', models.CharField(max_length=60)),
                ('desc', models.CharField(max_length=250)),
                ('display', models.BooleanField(default=True)),
                ('uploaded', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='importantdates',
            name='display',
            field=models.BooleanField(default=True),
        ),
    ]
