# Generated by Django 3.2 on 2021-07-21 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('runo', '0007_aboutschool'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutschool',
            name='slug',
        ),
    ]
