# Generated by Django 3.2 on 2021-07-21 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runo', '0008_remove_aboutschool_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Academics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='about/')),
                ('desc', models.CharField(default='Image description', max_length=250)),
                ('title', models.CharField(default='Title', max_length=250)),
                ('aboutBody', models.TextField()),
                ('publish', models.BooleanField(default=False)),
                ('published', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-published'],
            },
        ),
    ]
