# Generated by Django 3.2 on 2021-07-25 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runo', '0011_userclass'),
    ]

    operations = [
        migrations.AddField(
            model_name='userclass',
            name='prev_classes',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
