# Generated by Django 3.2 on 2021-07-25 06:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('runo', '0012_userclass_prev_classes'),
    ]

    operations = [
        migrations.AddField(
            model_name='userclass',
            name='in_class',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userclass',
            name='user',
            field=models.ManyToManyField(related_query_name='classes', to=settings.AUTH_USER_MODEL),
        ),
    ]
