# Generated by Django 3.2 on 2021-07-25 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runo', '0013_auto_20210725_0758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userclass',
            name='in_class',
            field=models.BooleanField(default=True),
        ),
    ]
