# Generated by Django 3.2 on 2021-07-26 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('runo', '0014_alter_userclass_in_class'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userclass',
            old_name='user',
            new_name='users',
        ),
    ]
