# Generated by Django 3.2 on 2021-07-26 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('runo', '0015_rename_user_userclass_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userclass',
            name='prev_classes',
        ),
    ]
