# Generated by Django 3.2 on 2021-07-27 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runo', '0018_auto_20210726_0701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userclass',
            name='Class',
            field=models.CharField(choices=[('1', 'Pre-Nursery'), ('2', 'Nursery 1'), ('3', 'Nursery 2'), ('4', 'Nursery 3'), ('5', 'Basic 1'), ('6', 'Basic 2'), ('7', 'Basic 3'), ('8', 'Basic 4'), ('9', 'Basic 5'), ('10', 'Basic 6')], default='1', max_length=30),
        ),
    ]
